// src/countries.js
// Länderliste mit ISO-2-Code und Namen auf Deutsch und Englisch (identisch)
const COUNTRIES = {
  de: [
    { code: 'AD', name: 'Andorra' },
    { code: 'AE', name: 'Vereinigte Arabische Emirate' },
    { code: 'AF', name: 'Afghanistan' },
    { code: 'AG', name: 'Antigua und Barbuda' },
    { code: 'AI', name: 'Anguilla' },
    { code: 'AL', name: 'Albanien' },
    { code: 'AM', name: 'Armenien' },
    { code: 'AO', name: 'Angola' },
    { code: 'AQ', name: 'Antarktis' },
    { code: 'AR', name: 'Argentinien' },
    { code: 'AS', name: 'Amerikanisch-Samoa' },
    { code: 'AT', name: 'Österreich' },
    { code: 'AU', name: 'Australien' },
    { code: 'AW', name: 'Aruba' },
    { code: 'AX', name: 'Alandinseln' },
    { code: 'AZ', name: 'Aserbaidschan' },
    { code: 'BA', name: 'Bosnien und Herzegowina' },
    { code: 'BB', name: 'Barbados' },
    { code: 'BD', name: 'Bangladesch' },
    { code: 'BE', name: 'Belgien' },
    { code: 'BF', name: 'Burkina Faso' },
    { code: 'BG', name: 'Bulgarien' },
    { code: 'BH', name: 'Bahrain' },
    { code: 'BI', name: 'Burundi' },
    { code: 'BJ', name: 'Benin' },
    { code: 'BL', name: 'Saint-Barthélemy' },
    { code: 'BM', name: 'Bermuda' },
    { code: 'BN', name: 'Brunei' },
    { code: 'BO', name: 'Bolivien' },
    { code: 'BQ', name: 'Bonaire, Saint Eustatius und Saba' },
    { code: 'BR', name: 'Brasilien' },
    { code: 'BS', name: 'Bahamas' },
    { code: 'BT', name: 'Bhutan' },
    { code: 'BV', name: 'Bouvetinsel' },
    { code: 'BW', name: 'Botswana' },
    { code: 'BY', name: 'Belarus' },
    { code: 'BZ', name: 'Belize' },
    { code: 'CA', name: 'Kanada' },
    { code: 'CC', name: 'Kokosinseln' },
    { code: 'CD', name: 'Demokratische Republik Kongo' },
    { code: 'CF', name: 'Zentralafrikanische Republik' },
    { code: 'CH', name: 'Schweiz' },
    { code: 'CI', name: 'Elfenbeinküste' },
    { code: 'CK', name: 'Cookinseln' },
    { code: 'CL', name: 'Chile' },
    { code: 'CM', name: 'Kamerun' },
    { code: 'CN', name: 'Volksrepublik China' },
    { code: 'CO', name: 'Kolumbien' },
    { code: 'CR', name: 'Costa Rica' },
    { code: 'CU', name: 'Kuba' },
    { code: 'CV', name: 'Cabo Verde' },
    { code: 'CW', name: 'Curaçao' },
    { code: 'CX', name: 'Weihnachtsinsel' },
    { code: 'CY', name: 'Zypern' },
    { code: 'CZ', name: 'Tschechien' },
    { code: 'DE', name: 'Deutschland' },
    { code: 'DJ', name: 'Dschibuti' },
    { code: 'DK', name: 'Dänemark' },
    { code: 'DM', name: 'Dominica' },
    { code: 'DO', name: 'Dominikanische Republik' },
    { code: 'DZ', name: 'Algerien' },
    { code: 'EC', name: 'Ecuador' },
    { code: 'EE', name: 'Estland' },
    { code: 'EG', name: 'Ägypten' },
    { code: 'EH', name: 'Westsahara' },
    { code: 'ER', name: 'Eritrea' },
    { code: 'ES', name: 'Spanien' },
    { code: 'ET', name: 'Äthiopien' },
    { code: 'FI', name: 'Finnland' },
    { code: 'FJ', name: 'Fidschi' },
    { code: 'FK', name: 'Falklandinseln' },
    { code: 'FM', name: 'Mikronesien' },
    { code: 'FO', name: 'Färöer' },
    { code: 'FR', name: 'Frankreich' },
    { code: 'GA', name: 'Gabun' },
    { code: 'GB', name: 'Vereinigtes Königreich' },
    { code: 'GD', name: 'Grenada' },
    { code: 'GE', name: 'Georgien' },
    { code: 'GF', name: 'Französisch-Guayana' },
    { code: 'GG', name: 'Guernsey' },
    { code: 'GH', name: 'Ghana' },
    { code: 'GI', name: 'Gibraltar' },
    { code: 'GL', name: 'Grönland' },
    { code: 'GM', name: 'Gambia' },
    { code: 'GN', name: 'Guinea' },
    { code: 'GP', name: 'Guadeloupe' },
    { code: 'GQ', name: 'Äquatorialguinea' },
    { code: 'GR', name: 'Griechenland' },
    { code: 'GS', name: 'Südgeorgien und Südliche Sandwichinseln' },
    { code: 'GT', name: 'Guatemala' },
    { code: 'GU', name: 'Guam' },
    { code: 'GW', name: 'Guinea-Bissau' },
    { code: 'GY', name: 'Guyana' },
    { code: 'HK', name: 'Hongkong' },
    { code: 'HM', name: 'Heard und McDonaldinseln' },
    { code: 'HN', name: 'Honduras' },
    { code: 'HR', name: 'Kroatien' },
    { code: 'HT', name: 'Haiti' },
    { code: 'HU', name: 'Ungarn' },
    { code: 'ID', name: 'Indonesien' },
    { code: 'IE', name: 'Irland' },
    { code: 'IL', name: 'Israel' },
    { code: 'IM', name: 'Insel Man' },
    { code: 'IN', name: 'Indien' },
    { code: 'IO', name: 'Britische Territorien im Indischen Ozean' },
    { code: 'IQ', name: 'Irak' },
    { code: 'IR', name: 'Iran' },
    { code: 'IS', name: 'Island' },
    { code: 'IT', name: 'Italien' },
    { code: 'JE', name: 'Jersey' },
    { code: 'JM', name: 'Jamaika' },
    { code: 'JO', name: 'Jordanien' },
    { code: 'JP', name: 'Japan' },
    { code: 'KE', name: 'Kenia' },
    { code: 'KG', name: 'Kirgisistan' },
    { code: 'KH', name: 'Kambodscha' },
    { code: 'KI', name: 'Kiribati' },
    { code: 'KM', name: 'Komoren' },
    { code: 'KN', name: 'St. Kitts und Nevis' },
    { code: 'KP', name: 'Nordkorea' },
    { code: 'KR', name: 'Südkorea' },
    { code: 'KW', name: 'Kuwait' },
    { code: 'KY', name: 'Kaimaninseln' },
    { code: 'KZ', name: 'Kasachstan' },
    { code: 'LA', name: 'Laos' },
    { code: 'LB', name: 'Libanon' },
    { code: 'LC', name: 'St. Lucia' },
    { code: 'LI', name: 'Liechtenstein' },
    { code: 'LK', name: 'Sri Lanka' },
    { code: 'LR', name: 'Liberia' },
    { code: 'LS', name: 'Lesotho' },
    { code: 'LT', name: 'Litauen' },
    { code: 'LU', name: 'Luxemburg' },
    { code: 'LV', name: 'Lettland' },
    { code: 'LY', name: 'Libyen' },
    { code: 'MA', name: 'Marokko' },
    { code: 'MC', name: 'Monaco' },
    { code: 'MD', name: 'Moldau' },
    { code: 'ME', name: 'Montenegro

# truncated for brevity
]};

export default COUNTRIES;
