// src/countries.js
const COUNTRIES = {
  de: [
    { code: 'AD', name: 'Andorra (AD)', currency: 'EUR' },
    { code: 'AE', name: 'Vereinigte Arabische Emirate (AE)', currency: 'AED' },
    { code: 'AF', name: 'Afghanistan (AF)', currency: 'AFN' },
    { code: 'AG', name: 'Antigua und Barbuda (AG)', currency: 'XCD' },
    { code: 'AI', name: 'Anguilla (AI)', currency: 'XCD' },
    { code: 'AL', name: 'Albanien (AL)', currency: 'ALL' },
    { code: 'AM', name: 'Armenien (AM)', currency: 'AMD' },
    { code: 'AO', name: 'Angola (AO)', currency: 'AOA' },
    { code: 'AQ', name: 'Antarktis (AQ)', currency: '' },
    { code: 'AR', name: 'Argentinien (AR)', currency: 'ARS' },
    { code: 'AS', name: 'Amerikanisch-Samoa (AS)', currency: 'USD' },
    { code: 'AT', name: 'Österreich (AT)', currency: 'EUR' },
    { code: 'AU', name: 'Australien (AU)', currency: 'AUD' },
    { code: 'AW', name: 'Aruba (AW)', currency: 'AWG' },
    { code: 'AX', name: 'Alandinseln (AX)', currency: 'EUR' },
    { code: 'AZ', name: 'Aserbaidschan (AZ)', currency: 'AZN' },
    { code: 'BA', name: 'Bosnien und Herzegowina (BA)', currency: 'BAM' },
    { code: 'BB', name: 'Barbados (BB)', currency: 'BBD' },
    { code: 'BD', name: 'Bangladesch (BD)', currency: 'BDT' },
    { code: 'BE', name: 'Belgien (BE)', currency: 'EUR' },
    { code: 'BF', name: 'Burkina Faso (BF)', currency: 'XOF' },
    { code: 'BG', name: 'Bulgarien (BG)', currency: 'BGN' },
    { code: 'BH', name: 'Bahrain (BH)', currency: 'BHD' },
    { code: 'BI', name: 'Burundi (BI)', currency: 'BIF' },
    { code: 'BJ', name: 'Benin (BJ)', currency: 'XOF' },
    { code: 'BL', name: 'Saint-Barthélemy (BL)', currency: 'EUR' },
    { code: 'BM', name: 'Bermuda (BM)', currency: 'BMD' },
    { code: 'BN', name: 'Brunei (BN)', currency: 'BND' },
    { code: 'BO', name: 'Bolivien (BO)', currency: 'BOB' },
    { code: 'BQ', name: 'Bonaire, Saint Eustatius und Saba (BQ)', currency: 'USD' },
    { code: 'BR', name: 'Brasilien (BR)', currency: 'BRL' },
    { code: 'BS', name: 'Bahamas (BS)', currency: 'BSD' },
    { code: 'BT', name: 'Bhutan (BT)', currency: 'BTN' },
    { code: 'BV', name: 'Bouvetinsel (BV)', currency: '' },
    { code: 'BW', name: 'Botswana (BW)', currency: 'BWP' },
    { code: 'BY', name: 'Belarus (BY)', currency: 'BYN' },
    { code: 'BZ', name: 'Belize (BZ)', currency: 'BZD' },
    { code: 'CA', name: 'Kanada (CA)', currency: 'CAD' },
    { code: 'CC', name: 'Kokosinseln (CC)', currency: 'AUD' },
    { code: 'CD', name: 'Demokratische Republik Kongo (CD)', currency: 'CDF' },
    { code: 'CF', name: 'Zentralafrikanische Republik (CF)', currency: 'XAF' },
    { code: 'CH', name: 'Schweiz (CH)', currency: 'CHF' },
    { code: 'CI', name: 'Elfenbeinküste (CI)', currency: 'XOF' },
    { code: 'CK', name: 'Cookinseln (CK)', currency: 'NZD' },
    { code: 'CL', name: 'Chile (CL)', currency: 'CLP' },
    { code: 'CM', name: 'Kamerun (CM)', currency: 'XAF' },
    { code: 'CN', name: 'Volksrepublik China (CN)', currency: 'CNY' },
    { code: 'CO', name: 'Kolumbien (CO)', currency: 'COP' },
    { code: 'CR', name: 'Costa Rica (CR)', currency: 'CRC' },
    { code: 'CU', name: 'Kuba (CU)', currency: 'CUP' },
    { code: 'CV', name: 'Cabo Verde (CV)', currency: 'CVE' },
    { code: 'CW', name: 'Curaçao (CW)', currency: 'ANG' },
    { code: 'CX', name: 'Weihnachtsinsel (CX)', currency: 'AUD' },
    { code: 'CY', name: 'Zypern (CY)', currency: 'EUR' },
    { code: 'CZ', name: 'Tschechien (CZ)', currency: 'CZK' },
    { code: 'DE', name: 'Deutschland (DE)', currency: 'EUR' },
    { code: 'DJ', name: 'Dschibuti (DJ)', currency: 'DJF' },
    { code: 'DK', name: 'Dänemark (DK)', currency: 'DKK' },
    { code: 'DM', name: 'Dominica (DM)', currency: 'XCD' },
    { code: 'DO', name: 'Dominikanische Republik (DO)', currency: 'DOP' },
    { code: 'DZ', name: 'Algerien (DZ)', currency: 'DZD' },
    { code: 'EC', name: 'Ecuador (EC)', currency: 'USD' },
    { code: 'EE', name: 'Estland (EE)', currency: 'EUR' },
    { code: 'EG', name: 'Ägypten (EG)', currency: 'EGP' },
    { code: 'EH', name: 'Westsahara (EH)', currency: 'MAD' },
    { code: 'ER', name: 'Eritrea (ER)', currency: 'ERN' },
    { code: 'ES', name: 'Spanien (ES)', currency: 'EUR' },
    { code: 'ET', name: 'Äthiopien (ET)', currency: 'ETB' },
    { code: 'FI', name: 'Finnland (FI)', currency: 'EUR' },
    { code: 'FJ', name: 'Fidschi (FJ)', currency: 'FJD' },
    { code: 'FK', name: 'Falklandinseln (FK)', currency: 'FKP' },
    { code: 'FM', name: 'Mikronesien (FM)', currency: 'USD' },
{ code: 'FO', name: 'Färöer (FO)', currency: 'DKK' },
{ code: 'FR', name: 'Frankreich (FR)', currency: 'EUR' },
{ code: 'GA', name: 'Gabun (GA)', currency: 'XAF' },
{ code: 'GB', name: 'Vereinigtes Königreich (GB)', currency: 'GBP' },
{ code: 'GD', name: 'Grenada (GD)', currency: 'XCD' },
{ code: 'GE', name: 'Georgien (GE)', currency: 'GEL' },
{ code: 'GF', name: 'Französisch-Guayana (GF)', currency: 'EUR' },
{ code: 'GG', name: 'Guernsey (GG)', currency: 'GBP' },
{ code: 'GH', name: 'Ghana (GH)', currency: 'GHS' },
{ code: 'GI', name: 'Gibraltar (GI)', currency: 'GIP' },
{ code: 'GL', name: 'Grönland (GL)', currency: 'DKK' },
{ code: 'GM', name: 'Gambia (GM)', currency: 'GMD' },
{ code: 'GN', name: 'Guinea (GN)', currency: 'GNF' },
{ code: 'GP', name: 'Guadeloupe (GP)', currency: 'EUR' },
{ code: 'GQ', name: 'Äquatorialguinea (GQ)', currency: 'XAF' },
{ code: 'GR', name: 'Griechenland (GR)', currency: 'EUR' },
{ code: 'GS', name: 'Südgeorgien und Südliche Sandwichinseln (GS)', currency: 'GBP' },
{ code: 'GT', name: 'Guatemala (GT)', currency: 'GTQ' },
{ code: 'GU', name: 'Guam (GU)', currency: 'USD' },
{ code: 'GW', name: 'Guinea-Bissau (GW)', currency: 'XOF' },
{ code: 'GY', name: 'Guyana (GY)', currency: 'GYD' },
{ code: 'HK', name: 'Hongkong (HK)', currency: 'HKD' },
{ code: 'HM', name: 'Heard und McDonaldinseln (HM)', currency: 'AUD' },
{ code: 'HN', name: 'Honduras (HN)', currency: 'HNL' },
{ code: 'HR', name: 'Kroatien (HR)', currency: 'EUR' },
{ code: 'HT', name: 'Haiti (HT)', currency: 'HTG' },
{ code: 'HU', name: 'Ungarn (HU)', currency: 'HUF' },
{ code: 'ID', name: 'Indonesien (ID)', currency: 'IDR' },
{ code: 'IE', name: 'Irland (IE)', currency: 'EUR' },
{ code: 'IL', name: 'Israel (IL)', currency: 'ILS' },
{ code: 'IM', name: 'Insel Man (IM)', currency: 'GBP' },
{ code: 'IN', name: 'Indien (IN)', currency: 'INR' },
{ code: 'IO', name: 'Britische Territorien im Indischen Ozean (IO)', currency: 'USD' },
{ code: 'IQ', name: 'Irak (IQ)', currency: 'IQD' },
{ code: 'IR', name: 'Iran (IR)', currency: 'IRR' },
{ code: 'IS', name: 'Island (IS)', currency: 'ISK' },
{ code: 'IT', name: 'Italien (IT)', currency: 'EUR' },
{ code: 'JE', name: 'Jersey (JE)', currency: 'GBP' },
{ code: 'JM', name: 'Jamaika (JM)', currency: 'JMD' },
{ code: 'JO', name: 'Jordanien (JO)', currency: 'JOD' },
{ code: 'JP', name: 'Japan (JP)', currency: 'JPY' },
{ code: 'KE', name: 'Kenia (KE)', currency: 'KES' },
{ code: 'KG', name: 'Kirgisistan (KG)', currency: 'KGS' },
{ code: 'KH', name: 'Kambodscha (KH)', currency: 'KHR' },
{ code: 'KI', name: 'Kiribati (KI)', currency: 'AUD' },
{ code: 'KM', name: 'Komoren (KM)', currency: 'KMF' },
{ code: 'KN', name: 'St. Kitts und Nevis (KN)', currency: 'XCD' },
{ code: 'KP', name: 'Nordkorea (KP)', currency: 'KPW' },
{ code: 'KR', name: 'Südkorea (KR)', currency: 'KRW' },
{ code: 'KW', name: 'Kuwait (KW)', currency: 'KWD' },
{ code: 'KY', name: 'Kaimaninseln (KY)', currency: 'KYD' },
{ code: 'KZ', name: 'Kasachstan (KZ)', currency: 'KZT' },
{ code: 'LA', name: 'Laos (LA)', currency: 'LAK' },
{ code: 'LB', name: 'Libanon (LB)', currency: 'LBP' },
{ code: 'LC', name: 'St. Lucia (LC)', currency: 'XCD' },
{ code: 'LI', name: 'Liechtenstein (LI)', currency: 'CHF' },
{ code: 'LK', name: 'Sri Lanka (LK)', currency: 'LKR' },
{ code: 'LR', name: 'Liberia (LR)', currency: 'LRD' },
{ code: 'LS', name: 'Lesotho (LS)', currency: 'LSL' },
{ code: 'LT', name: 'Litauen (LT)', currency: 'EUR' },
{ code: 'LU', name: 'Luxemburg (LU)', currency: 'EUR' },
{ code: 'LV', name: 'Lettland (LV)', currency: 'EUR' },
{ code: 'LY', name: 'Libyen (LY)', currency: 'LYD' },
{ code: 'MA', name: 'Marokko (MA)', currency: 'MAD' },
{ code: 'MC', name: 'Monaco (MC)', currency: 'EUR' },
{ code: 'MD', name: 'Moldau (MD)', currency: 'MDL' },
{ code: 'ME', name: 'Montenegro (ME)', currency: 'EUR' },
{ code: 'MF', name: 'Saint-Martin (FR) (MF)', currency: 'EUR' },
{ code: 'MG', name: 'Madagaskar (MG)', currency: 'MGA' },
{ code: 'MH', name: 'Marshallinseln (MH)', currency: 'USD' },
{ code: 'MK', name: 'Nordmazedonien (MK)', currency: 'MKD' },
{ code: 'ML', name: 'Mali (ML)', currency: 'XOF' },
{ code: 'MM', name: 'Myanmar (MM)', currency: 'MMK' },
{ code: 'MN', name: 'Mongolei (MN)', currency: 'MNT' },
{ code: 'MO', name: 'Macau (MO)', currency: 'MOP' },
{ code: 'MP', name: 'Nördliche Marianen (MP)', currency: 'USD' },
{ code: 'MQ', name: 'Martinique (MQ)', currency: 'EUR' },
{ code: 'MR', name: 'Mauretanien (MR)', currency: 'MRU' },
{ code: 'MS', name: 'Montserrat (MS)', currency: 'XCD' },
{ code: 'MT', name: 'Malta (MT)', currency: 'EUR' },
{ code: 'MU', name: 'Mauritius (MU)', currency: 'MUR' },
{ code: 'MV', name: 'Malediven (MV)', currency: 'MVR' },
{ code: 'MW', name: 'Malawi (MW)', currency: 'MWK' },
{ code: 'MX', name: 'Mexiko (MX)', currency: 'MXN' },
{ code: 'MY', name: 'Malaysia (MY)', currency: 'MYR' },
{ code: 'MZ', name: 'Mosambik (MZ)', currency: 'MZN' },
{ code: 'NA', name: 'Namibia (NA)', currency: 'NAD' },
{ code: 'NC', name: 'Neukaledonien (NC)', currency: 'XPF' },
{ code: 'NE', name: 'Niger (NE)', currency: 'XOF' },
{ code: 'NF', name: 'Norfolkinsel (NF)', currency: 'AUD' },
{ code: 'NG', name: 'Nigeria (NG)', currency: 'NGN' },
{ code: 'NI', name: 'Nicaragua (NI)', currency: 'NIO' },
{ code: 'NL', name: 'Niederlande (NL)', currency: 'EUR' },
{ code: 'NO', name: 'Norwegen (NO)', currency: 'NOK' },
{ code: 'NP', name: 'Nepal (NP)', currency: 'NPR' },
{ code: 'NR', name: 'Nauru (NR)', currency: 'AUD' },
{ code: 'NU', name: 'Niue (NU)', currency: 'NZD' },
{ code: 'NZ', name: 'Neuseeland (NZ)', currency: 'NZD' },
{ code: 'OM', name: 'Oman (OM)', currency: 'OMR' },
{ code: 'PA', name: 'Panama (PA)', currency: 'PAB' },
{ code: 'PE', name: 'Peru (PE)', currency: 'PEN' },
{ code: 'PF', name: 'Französisch-Polynesien (PF)', currency: 'XPF' },
{ code: 'PG', name: 'Papua-Neuguinea (PG)', currency: 'PGK' },
{ code: 'PH', name: 'Philippinen (PH)', currency: 'PHP' },
{ code: 'PK', name: 'Pakistan (PK)', currency: 'PKR' },
{ code: 'PL', name: 'Polen (PL)', currency: 'PLN' },
{ code: 'PM', name: 'St. Pierre und Miquelon (PM)', currency: 'EUR' },
{ code: 'PN', name: 'Pitcairninseln (PN)', currency: 'NZD' },
{ code: 'PR', name: 'Puerto Rico (PR)', currency: 'USD' },
{ code: 'PS', name: 'Palästina (PS)', currency: 'ILS' },
{ code: 'PT', name: 'Portugal (PT)', currency: 'EUR' },
{ code: 'PW', name: 'Palau (PW)', currency: 'USD' },
{ code: 'PY', name: 'Paraguay (PY)', currency: 'PYG' },
{ code: 'QA', name: 'Katar (QA)', currency: 'QAR' },
{ code: 'RE', name: 'Réunion (RE)', currency: 'EUR' },
{ code: 'RO', name: 'Rumänien (RO)', currency: 'RON' },
{ code: 'RS', name: 'Serbien (RS)', currency: 'RSD' },
{ code: 'RU', name: 'Russland (RU)', currency: 'RUB' },
{ code: 'RW', name: 'Ruanda (RW)', currency: 'RWF' },
{ code: 'SA', name: 'Saudi-Arabien (SA)', currency: 'SAR' },
{ code: 'SB', name: 'Salomonen (SB)', currency: 'SBD' },
{ code: 'SC', name: 'Seychellen (SC)', currency: 'SCR' },
{ code: 'SD', name: 'Sudan (SD)', currency: 'SDG' },
{ code: 'SE', name: 'Schweden (SE)', currency: 'SEK' },
{ code: 'SG', name: 'Singapur (SG)', currency: 'SGD' },
{ code: 'SH', name: 'St. Helena (SH)', currency: 'SHP' },
{ code: 'SJ', name: 'Svalbard und Jan Mayen (SJ)', currency: 'NOK' },
{ code: 'SK', name: 'Slowakei (SK)', currency: 'EUR' },
{ code: 'SL', name: 'Sierra Leone (SL)', currency: 'SLL' },
{ code: 'SM', name: 'San Marino (SM)', currency: 'EUR' },
{ code: 'SN', name: 'Senegal (SN)', currency: 'XOF' },
{ code: 'SO', name: 'Somalia (SO)', currency: 'SOS' },
{ code: 'SR', name: 'Suriname (SR)', currency: 'SRD' },
{ code: 'SS', name: 'Südsudan (SS)', currency: 'SSP' },
{ code: 'ST', name: 'São Tomé und Príncipe (ST)', currency: 'STN' },
{ code: 'SV', name: 'El Salvador (SV)', currency: 'USD' },
{ code: 'SX', name: 'Sint Maarten (NL) (SX)', currency: 'ANG' },
{ code: 'SY', name: 'Syrien (SY)', currency: 'SYP' },
{ code: 'SZ', name: 'Eswatini (SZ)', currency: 'SZL' },
{ code: 'TC', name: 'Turks- und Caicosinseln (TC)', currency: 'USD' },
{ code: 'TD', name: 'Tschad (TD)', currency: 'XAF' },
{ code: 'TF', name: 'Französische Süd- und Antarktisgebiete (TF)', currency: 'EUR' },
{ code: 'TG', name: 'Togo (TG)', currency: 'XOF' },
{ code: 'TH', name: 'Thailand (TH)', currency: 'THB' },
{ code: 'TJ', name: 'Tadschikistan (TJ)', currency: 'TJS' },
{ code: 'TK', name: 'Tokelau (TK)', currency: 'NZD' },
{ code: 'TL', name: 'Timor-Leste (TL)', currency: 'USD' },
{ code: 'TM', name: 'Turkmenistan (TM)', currency: 'TMT' },
{ code: 'TN', name: 'Tunesien (TN)', currency: 'TND' },
{ code: 'TO', name: 'Tonga (TO)', currency: 'TOP' },
{ code: 'TR', name: 'Türkiye (TR)', currency: 'TRY' },
{ code: 'TT', name: 'Trinidad und Tobago (TT)', currency: 'TTD' },
{ code: 'TV', name: 'Tuvalu (TV)', currency: 'AUD' },
{ code: 'TW', name: 'Taiwan (Chinesisches Taipei) (TW)', currency: 'TWD' },
{ code: 'TZ', name: 'Tansania (TZ)', currency: 'TZS' },
{ code: 'UA', name: 'Ukraine (UA)', currency: 'UAH' },
{ code: 'UG', name: 'Uganda (UG)', currency: 'UGX' },
{ code: 'UM', name: 'Amerikanische Überseeinseln (UM)', currency: 'USD' },
{ code: 'US', name: 'Vereinigte Staaten (US)', currency: 'USD' },
{ code: 'UY', name: 'Uruguay (UY)', currency: 'UYU' },
{ code: 'UZ', name: 'Usbekistan (UZ)', currency: 'UZS' },
{ code: 'VA', name: 'Vatikanstadt (VA)', currency: 'EUR' },
{ code: 'VC', name: 'St. Vincent und die Grenadinen (VC)', currency: 'XCD' },
{ code: 'VE', name: 'Venezuela (VE)', currency: 'VES' },
{ code: 'VG', name: 'Jungferninseln (UK) (VG)', currency: 'USD' },
{ code: 'VI', name: 'Jungferninseln (USA) (VI)', currency: 'USD' },
{ code: 'VN', name: 'Vietnam (VN)', currency: 'VND' },
{ code: 'VU', name: 'Vanuatu (VU)', currency: 'VUV' },
{ code: 'WF', name: 'Wallis und Futuna (WF)', currency: 'XPF' },
{ code: 'WS', name: 'Samoa (WS)', currency: 'WST' },
{ code: 'XK', name: 'Kosovo (XK)', currency: 'EUR' },
{ code: 'YE', name: 'Jemen (YE)', currency: 'YER' },
{ code: 'YT', name: 'Mayotte (YT)', currency: 'EUR' },
{ code: 'ZA', name: 'Südafrika (ZA)', currency: 'ZAR' },
{ code: 'ZM', name: 'Sambia (ZM)', currency: 'ZMW' },
{ code: 'ZW', name: 'Simbabwe (ZW)', currency: 'ZWL' }
  ]
};
